# Generated by Django 3.1.4 on 2021-01-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imię', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('klasa', models.CharField(max_length=4)),
                ('opis', models.TextField(blank=True, max_length=300)),
                ('oddane', models.BooleanField(default=False)),
                ('zadanie', models.FileField(upload_to='')),
            ],
        ),
    ]
