# Generated by Django 3.1.4 on 2021-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectToUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=300)),
                ('project', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
