# Generated by Django 3.1.4 on 2021-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210109_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttocreate',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
