# Generated by Django 3.1.4 on 2021-01-09 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_projecttocreate_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttocreate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projecttoupload',
            name='name',
        ),
        migrations.AddField(
            model_name='projecttocreate',
            name='project_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttocreate',
            name='your_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttoupload',
            name='project_name',
            field=models.CharField(default='project', max_length=50),
        ),
    ]
