# Generated by Django 3.1.4 on 2021-01-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210109_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttocreate',
            name='done',
        ),
        migrations.AddField(
            model_name='projecttoupload',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projecttoupload',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
